export interface VRChatWorld {
    authorId: string;
    authorName: string;
    capacity: number;
    created_at: string;
    defaultContentSettings: Record<string, string>;
    description: string;
    favorites: number;
    featured: boolean;
    heat: number;
    id: string;
    imageUrl: string;
    instances: string[];
    labsPublicationDate: string;
    name: string;
    occupants: number;
    organization: string;
    popularity: number;
    previewYoutubeId: string | null;
    privateOccupants: number;
    publicOccupants: number;
    publicationDate: string;
    recommendedCapacity: number;
    releaseStatus: string;
    tags: string[];
    thumbnailImageUrl: string;
    udonProducts: string[];
    unityPackages: string[];
    updated_at: string;
    urlList: string[];
    version: number;
    visits: number;
}
